### PR TITLE
Add mental health question

### PR DESCRIPTION
**Pull request by KerronKing**
Added mental health question to the questionnaire. "MentalWarning" component giving a strange error on my side though. Not sure what's causing this.

### CODE REVIEW

**Comment by turbosnail9** [comment]
@KerronKing  can you provide some more details on the error? Perhaps some screenshots and any behaviours in the app that are unwanted.

**Comment by KerronKing** [comment]
No problem.

**Comment by KerronKing** [comment]
Clicking no on all questions, including the "mental health" addition gives a normal response, as follows
Screenshot 2020-03-26 at 3 20 13 PM

Clicking yes, yields the following response:
Screenshot 2020-03-26 at 3 19 42 PM

The import is seemingly not being recognized in the reducer file from my view.

**Review by DavidNeiOs — CHANGES_REQUESTED** [review]
the error is being shown because you need to add 

```js
// src/components/warnings/index.js
export * from "./mentalWarning"
```

**Review by DavidNeiOs — APPROVED** [review]

**Comment by DavidNeiOs** [comment]
Looks good @KerronKing merged !

**Pull request merged**
